# Generated by Django 4.2.7 on 2023-11-15 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_petpaluser_is_staff_alter_petpaluser_is_superuser'),
        ('petListing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petlisting',
            name='shelter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pet_listings', to='accounts.petshelter'),
        ),
    ]
