# Generated by Django 4.2.7 on 2023-12-12 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('comments', '0003_comment_is_reply_comment_parent_comment_and_more'),
        ('notifications', '0002_remove_notification_related_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='recipient_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_recipient', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.comment'),
        ),
    ]
