# Generated by Django 4.2.7 on 2023-12-12 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comment_is_reply_comment_parent_comment_and_more'),
        ('notifications', '0004_remove_notification_recipient_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='related_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.comment'),
        ),
    ]
